config/routes.rb
Rails.application.routes.draw do
  resources :notebooks do
    resources :cells do
      post 'run_cell', on: :member
    end
  end
  # put 'run/notebook/:notebook_id/cell/:id', to: 'cells#run', as: 'run_cell'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "notebooks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cell.rb
class Cell < ApplicationRecord
  belongs_to :notebook

  validates :content, presence: true
  validates :cell_type, inclusion: { in: [0, 1, 2], message: "%{value} is invalid." }
end

app/models/cell_type.rb
class CellType < ApplicationRecord
end

app/models/notebook.rb
class Notebook < ApplicationRecord
  has_many :cells, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cells_controller.rb
class CellsController < ApplicationController
  before_action :set_cell, only: %i[ show edit update destroy ]

  # GET /cells or /cells.json
  def index
    @cells = Cell.all
  end

  # GET /cells/1 or /cells/1.json
  def show
  end

  # GET /cells/new
  def new
    @cell = Cell.new
    @cell.notebook = Notebook.find(params[:notebook_id])
  end

  # GET /cells/1/edit
  def edit
  end

  # POST /cells or /cells.json
  def create
    @cell = Cell.new(cell_params)
    @cell.notebook = Notebook.find(params[:notebook_id])

    respond_to do |format|
      if @cell.save
        format.html { redirect_to notebook_url(@cell.notebook), notice: "Cell was successfully created." }
        format.json { render :show, status: :created, location: @cell }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cells/1 or /cells/1.json
  def update
    respond_to do |format|
      if @cell.update(cell_params)
        format.html { redirect_to cell_url(@cell), notice: "Cell was successfully updated." }
        format.json { render :show, status: :ok, location: @cell }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cell.errors, status: :unprocessable_entity }
      end
    end
  end

  def run_cell
    @cell = Cell.find(params[:id])
    code = @cell.content
    @cell.output = eval_with_captured_stdout{ eval(code) }

    respond_to do |format|
      if @cell.save!
        format.html { redirect_to notebook_url(@cell.notebook), notice: "Cell was successfully updated." }
        format.json { render :show, status: :ok, location: @cell }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cells/1 or /cells/1.json
  def destroy
    @cell.destroy!

    respond_to do |format|
      format.html { redirect_to cells_url, notice: "Cell was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cell
      @cell = Cell.find(cell_params)
    end
    
    def set_notebook
      @notebook = Notebook.find(params[:notebook_id])
    end

    # Only allow a list of trusted parameters through.
    def cell_params
      params.require(:cell).permit(:cell_type, :content, :output, :notebook_id)
    end

    def eval_with_captured_stdout
      original_stdout = $stdout
      $stdout = StringIO.new
      yield                      
      $stdout.string
    rescue Exception => e
      $stdout.puts e.message
      $stdout.puts e.backtrace
      $stdout.string
    ensure
      $stdout = original_stdout
    end

end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  before_action :set_notebook, only: %i[ show edit update destroy ]

  # GET /notebooks or /notebooks.json
  def index
    @notebooks = Notebook.all
  end

  # GET /notebooks/1 or /notebooks/1.json
  def show
  end

  # GET /notebooks/new
  def new
    @notebook = Notebook.new
  end

  # GET /notebooks/1/edit
  def edit
  end

  # POST /notebooks or /notebooks.json
  def create
    @notebook = Notebook.new(notebook_params)

    respond_to do |format|
      if @notebook.save
        format.html { redirect_to notebook_url(@notebook), notice: "Notebook was successfully created." }
        format.json { render :show, status: :created, location: @notebook }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notebooks/1 or /notebooks/1.json
  def update
    respond_to do |format|
      if @notebook.update(notebook_params)
        format.html { redirect_to notebook_url(@notebook), notice: "Notebook was successfully updated." }
        format.json { render :show, status: :ok, location: @notebook }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notebooks/1 or /notebooks/1.json
  def destroy
    @notebook.destroy!

    respond_to do |format|
      format.html { redirect_to notebooks_url, notice: "Notebook was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notebook
      @notebook = Notebook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notebook_params
      params.require(:notebook).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cells_helper.rb
module CellsHelper
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/views/cells/_cell.html.erb
<div id="<%= dom_id cell %>">
  <p>
    <strong>Type:</strong>
    <%= cell.type %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= cell.content %>
  </p>

  <p>
    <strong>Output:</strong>
    <%= cell.output %>
  </p>

  <p>
    <strong>Notebook:</strong>
    <%= cell.notebook_id %>
  </p>

</div>

app/views/cells/_form.html.erb
<%= form_with(model: cell, url: url) do |form| %>
  <% if cell.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cell.errors.count, "error") %> prohibited this cell from being saved:</h2>

      <ul>
        <% cell.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cell_type, style: "display: block" %>
    <%= form.select :cell_type, CellType.all.collect { |g| [g.label, g.value] }, include_blank: false %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cells/edit.html.erb
<h1>Editing cell</h1>

<%= render "form", cell: @cell %>

<br>

<div>
  <%= link_to "Show this cell", @cell %> |
  <%= link_to "Back to cells", cells_path %>
</div>

app/views/cells/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cells</h1>

<div id="cells">
  <% @cells.each do |cell| %>
    <%= render cell %>
    <p>
      <%= link_to "Show this cell", cell %>
    </p>
  <% end %>
</div>

<%= link_to "New cell", new_cell_path %>

app/views/cells/new.html.erb
<h1>New cell</h1>

<%= render "form", cell: @cell, url: notebook_cells_path(@cell.notebook, @cell) %>

<br>

<div>
  <%= link_to "Back to notebook", notebook_path(@cell.notebook) %>
</div>

app/views/cells/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cell %>

<div>
  <%= link_to "Edit this cell", edit_cell_path(@cell) %> |
  <%= link_to "Back to cells", cells_path %>

  <%= button_to "Destroy this cell", @cell, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notebooks/_form.html.erb
<%= form_with(model: notebook) do |form| %>
  <% if notebook.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(notebook.errors.count, "error") %> prohibited this notebook from being saved:</h2>

      <ul>
        <% notebook.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/notebooks/_notebook.html.erb
<h1><%= notebook.title %></h1>
<%= button_to "Delete notebook", notebook_path(notebook), method: :delete %>

app/views/notebooks/edit.html.erb
<h1>Editing notebook</h1>

<%= render "form", notebook: @notebook %>

<br>

<div>
  <%= link_to "Show this notebook", @notebook %> |
  <%= link_to "Back to notebooks", notebooks_path %>
</div>

app/views/notebooks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Notebooks</h1>

<div id="notebooks">
  <% @notebooks.each do |notebook| %>
    <%= render notebook %>
    <p>
      <%= link_to "Show this notebook", notebook %>
    </p>
  <% end %>
</div>

<%= link_to "New notebook", new_notebook_path %>

app/views/notebooks/new.html.erb
<h1>New notebook</h1>

<%= render "form", notebook: @notebook %>

<br>

<div>
  <%= link_to "Back to notebooks", notebooks_path %>
</div>

app/views/notebooks/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <%= link_to "Edit this notebook", edit_notebook_path(@notebook) %> |
  <%= link_to "Back to notebooks", notebooks_path %>
</div>

<%= render @notebook %>

<br/>
<%= link_to "Add cell", new_notebook_cell_path(@notebook) %>
<br/>
<br/>

<div class="cell-wrapper">
  <% @notebook.cells.each do |cell| %>
    <div class="cell">
      <% if cell.cell_type == 0 %>
        <div>
          <%= button_to "Run cell", run_cell_notebook_cell_path(@notebook, cell), method: :post %>
          <br/>
          <pre><code><%= cell.content %></code></pre>
        </div>
      <% else %>
        <p><%= cell.content %></p>
      <% end %>

      <% if !cell.output.nil? && !cell.output.empty? %>
        <div class="output" style="max-height: 10rem; overflow: auto">
          <pre><code>&gt; <%= cell.output %></code></pre>
        </div>
      <% end %>
    </div>
  <% end %>
</div>